config/routes.rb
Zenfocus::Application.routes.draw do
  resources :dummies

  devise_for :users

  root :to => 'static#index'

  resources :static
  resources :notes
  resources :posts do
    get 'vote', :as => :vote
  end

  match 'about', :to => 'static#about'
  match 'help', :to => 'static#help'

end

app/models/dummy.rb
class Dummy < ActiveRecord::Base
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :body, :presence => true

  # current active
  #
  # determines if the most recent task is active.
  # if it is, return it. if it is not, return nil.
  # need to nil check..
  def current
    current_post = Post.last

    # makes 2 checks.
    # 1. if the item isn't nil. (sanity check)
    # 2. if the task timed out yet. completed time > time now.
    if current_post != nil # and current_post.completed_at > Time.now.utc
      current_post
    else
      nil
    end
  end

  # parse time
  #
  # method to parse the time value out of a string using some escape code.
  # for now. i'm just assuming the first word of with the '+' prefix
  # will be used.
  #
  # buggy... sorta basically i don't want this to be called every time.
  # just on update.
  def parse_time
    # add a default time for a task.
    length_of_task = Time.now + 15.minutes

    # splits the entered text.
    sentence = body.split ' '
    esc_code = sentence.first

    # determines if the word is long enough.
    # if it was long enough, split the word into the necessary code.
    if esc_code.length >= 2
       esc_code_prefix = esc_code[0]
       esc_code_suffix = esc_code[1..-1]
    end

    # checks for valid escape sequence to parse.
    if esc_code_prefix == "+" and esc_code_suffix.match /\d/
      # set time specified by user.
      length_of_task = Time.now + (esc_code_suffix.to_i * 60)
      # remove the escape code from the string.
      sentences = body.split ' ', 2
      self.body = sentences[1]
    end

    # set the completed at time field.
    self.completed_at = length_of_task
    
  end


  # NOTE.
  #
  # columns in play.
  # completed_task, completed_at, body.
  #
  # completed_task (0=no, 1=yes)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/dummies_controller.rb
class DummiesController < ApplicationController
  # GET /dummies
  # GET /dummies.xml
  def index
    @dummies = Dummy.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dummies }
    end
  end

  # GET /dummies/1
  # GET /dummies/1.xml
  def show
    @dummy = Dummy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dummy }
    end
  end

  # GET /dummies/new
  # GET /dummies/new.xml
  def new
    @dummy = Dummy.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dummy }
    end
  end

  # GET /dummies/1/edit
  def edit
    @dummy = Dummy.find(params[:id])
  end

  # POST /dummies
  # POST /dummies.xml
  def create
    @dummy = Dummy.new(params[:dummy])

    respond_to do |format|
      if @dummy.save
        format.html { redirect_to(@dummy, :notice => 'Dummy was successfully created.') }
        format.xml  { render :xml => @dummy, :status => :created, :location => @dummy }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dummy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dummies/1
  # PUT /dummies/1.xml
  def update
    @dummy = Dummy.find(params[:id])

    respond_to do |format|
      if @dummy.update_attributes(params[:dummy])
        format.html { redirect_to(@dummy, :notice => 'Dummy was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dummy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dummies/1
  # DELETE /dummies/1.xml
  def destroy
    @dummy = Dummy.find(params[:id])
    @dummy.destroy

    respond_to do |format|
      format.html { redirect_to(dummies_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.xml
  def index
    @notes = Note.all

    # my stuff
    @note = Note.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to(@note, :notice => 'Note was successfully created.') }
        format.xml  { render :xml => @note, :status => :created, :location => @note }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(@note, :notice => 'Note was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(notes_url) }
      format.xml  { head :ok }
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # using devise authentication.
  before_filter :authenticate_user!

  def index
    @posts = Post.all
    @post = Post.new

    # load current active post if it exist.
    @post_current_active = @post.current

    respond_to do |format|
      format.html
    end
  end

  def create
    @post = Post.new(params[:post])
    @post.parse_time

    respond_to do |format|
      if @post.save
        format.html {
          redirect_to(posts_url, :notice => 'Post was successfully created.')
        }
        format.js {
          # load current active post if it exist.
          @post_current_active = @post.current
        }
      else
        format.html { redirect_to(posts_url) }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.js {
        # load current active post if it exist.
        @post_current_active = @post.current
      }
    end
  end

  # define a vote that a user makes on each post.
  def update
    @post = Post.find(params[:id])
    Rails.logger.debug("date c" + @post.completed_at.to_s)
    Rails.logger.debug("date u" + @post.updated_at.to_s)
    @post.completed_task = params[:completed_task]

    respond_to do |format|
      if @post.save
        # refresh all post if the models was updated.
        @posts = Post.all
        format.html { redirect_to(posts_url, :notice => 'Post was successfully updated.') }
        format.js
      else
        format.html { redirect_to(posts_url) }
        format.js
      end
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def about
    respond_to do |format|
      format.html
    end
  end

  def help
    respond_to do |format|
      format.html
    end
  end

  def index
    if user_signed_in?
      redirect_to :controller => "posts"
    else
      respond_to do |format|
        format.html
      end
    end
  end
  
end

app/helpers/dummies_helper.rb
module DummiesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/dummies/_form.html.erb
<%= form_for(@dummy) do |f| %>
  <% if @dummy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dummy.errors.count, "error") %> prohibited this dummy from being saved:</h2>

      <ul>
      <% @dummy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dummies/edit.html.erb
<h1>Editing dummy</h1>

<%= render 'form' %>

<%= link_to 'Show', @dummy %> |
<%= link_to 'Back', dummies_path %>

app/views/dummies/index.html.erb
<h1>Listing dummies</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dummies.each do |dummy| %>
  <tr>
    <td><%= dummy.title %></td>
    <td><%= dummy.body %></td>
    <td><%= link_to 'Show', dummy %></td>
    <td><%= link_to 'Edit', edit_dummy_path(dummy) %></td>
    <td><%= link_to 'Destroy', dummy, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dummy', new_dummy_path %>

app/views/dummies/new.html.erb
<h1>New dummy</h1>

<%= render 'form' %>

<%= link_to 'Back', dummies_path %>

app/views/dummies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @dummy.title %>
</p>

<p>
  <b>Body:</b>
  <%= @dummy.body %>
</p>


<%= link_to 'Edit', edit_dummy_path(@dummy) %> |
<%= link_to 'Back', dummies_path %>

app/views/layouts/_htmlhead.html.erb
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Zenfocus</title>

<!-- rails stuff -->
<%= stylesheet_link_tag :all %>
<%= csrf_meta_tag %>

<!-- load application, jquery, and rails.js -->
<%= javascript_include_tag "application", "jquery", "rails" %>

<!-- 960px stuff -->
<%= stylesheet_link_tag "reset" %>
<%= stylesheet_link_tag "text" %>
<%= stylesheet_link_tag "960" %>

<!-- my customizations off 960px -->
<%= stylesheet_link_tag "myLayout" %>
<%= stylesheet_link_tag "myTable" %>
<%= stylesheet_link_tag "myText" %>
<%= stylesheet_link_tag "myForm" %>

app/views/layouts/_navfooter.html.erb
<!-- FOOTER -->
<div class="grid_12" id="nav_footer">
    <p id="nav_footer_links">
        <!--
            putting "/" in front on the controller so it does not nest with
            any other controller like devise.
        -->
        <%= link_to 'zenfoc.us' , :controller => '/posts', :action => 'index' %>
        |
        <%= link_to 'about' , :controller => '/static', :action => 'about' %>
        |
        <%= link_to 'help' , :controller => '/static', :action => 'help' %>
    </p>
</div>

<div class="clear"></div>

app/views/layouts/_navheader.html.erb
<!-- LOGO -->
<div class="grid_4" id="nav_header">
    <p id="nav_header_logo">
      zenfoc.us
    </p>
</div>

<!-- login / registration -->
<div class="grid_8" id="nav_header">
    <p id="nav_header_links">
        <!-- devise login. -->
        <% if user_signed_in? %>
          <%= current_user.email %>
          <%= link_to 'log out' , '/users/sign_out/' %>
        <% else %>
          <%= link_to 'log in' , '/users/sign_in/' %>
          |
          <%= link_to 'register', '/users/sign_up/' %>
        <% end %>
    </p>
</div>

<div class="clear"></div>

app/views/layouts/_navmain.html.erb
<!-- MAIN BODY -->
<div class="grid_9" id="nav_main">
    <%= yield %>
</div>

app/views/layouts/_navside.html.erb
<!-- side panel. used for login prompts, etc... -->
<div class="grid_3" id="nav_side">
    <p>sidebar</p>
</div>

<div class="clear"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!--
  A simple layout of for this website.
  all of the main elements are in partials in the same directory.
-->
<html lang="en">

<head>
    <%= render :partial => "layouts/htmlhead" %>
</head>

<body>

<div class="container_12">

    <%= render :partial => "layouts/navheader" %>
    <%= render :partial => "layouts/navmain" %>
    <%= render :partial => "layouts/navside" %>
    <%= render :partial => "layouts/navfooter" %>

</div>

</body>

</html>

app/views/notes/_form.html.erb
<%= form_for(@note, :remote => true) do |f| %>
  <!-- errors -->
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/notes/create.js.erb
$('#notes').prepend('<%= escape_javascript(render(@note)) %>');
$('#notes > li:first').effect('highlight', {}, 3000);
$('#note_form > form')[0].reset();

app/views/notes/destroy.js.erb
$('#<%= dom_id(@note) %>').css('background', 'red');
$('#<%= dom_id(@note) %>').hide("fade", {}, 1500);

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>
<br /><br />

<div id="post_form">
  <%= render 'form' %>
</div>

<ul id="posts">
  <%= render :partial => @notes.reverse %>
</ul>

<table>

  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @notes.each do |note| %>
    <tr>
      <td><%= note.title %></td>
      <td><%= note.content %></td>
      <td><%= link_to 'Show', note %></td>
      <td><%= link_to 'Edit', edit_note_path(note) %></td>
      <td><%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Content:</b>
  <%= @note.content %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/posts/_current.html.erb
<!-- current post -->
<div id="post_current">

  <!-- text of task -->
  <div id="post_current_task_text" class="grid_6 alpha">
    <h6>Current Task:</h6>
    <p id="post_current_task_text_actual">
      <%= @post_current_active.body %>
    </p>
  </div>

  <!-- timer. -->
  <div id="post_current_task_timer" class="grid_3 omega">
    <h6>Complete in:</h6>
    <p id="countbox"></p>
  </div>

  <!-- 960px. indicates that row is complete. -->
  <div class="clear"></div>
  
  <!-- need to figure how to load the correct time -->
  <% javascript_tag do %>
  $(document).ready(function() {
    countdown_secs( 
      <%= @post_current_active.completed_at - Time.now.utc %> 
    );
  });
  <% end %>

</div>

app/views/posts/_form.html.erb
<div id="post_form">
  <%= form_for(@post, :remote => true) do |f| %>

    <div id="form_post_field" class="grid_8 alpha">
      <%= f.text_field :body %>
    </div>

    <div id="form_post_submit" class="grid_1 omega">
      <%= f.submit 'Go' %>
    </div>
    
    <!-- 960px. indicates that row is complete. -->
    <div class="clear"></div>

  <% end %>
</div>

app/views/posts/_post.html.erb
<%= content_tag_for(:tr, post) do %>
  <!-- using if/else block to determine if a tick / cross should be displayed -->
  <% if post.completed_task == 1 %>
    <td><%= image_tag("tick.png", :alt => "+") %></td>
  <% else %>
    <td><%= image_tag("cross.png", :alt => "X") %></td>
  <% end %>
  <td><%= post.body %></td>
  <td><%= post.completed_at %></td>
  <td><%= link_to image_tag('delete.png'), post, :confirm => 'Are you sure?', :method => :delete, :remote => true %>
      <%= link_to image_tag('thumb_up.png'), post_path(:id => post.id, :completed_task => 1), :method => :put, :remote => true %>
      <%= link_to image_tag('thumb_down.png'), post_path(:id => post.id, :completed_task => 0), :method => :put, :remote => true %>
  </td>
<% end %>

app/views/posts/_table.html.erb
<table id="posts">
  <!-- labels for colums -->
  <thead>
    <tr>
      <th id="post_task_complete"> </th>
      <th id="post_task_text">task</th>
      <th id="post_task_date">date completed</th>
      <th id="post_task_options">options   </th>
    </tr>
  </thead>

  <!-- table contents rendered in a partial called _post -->
  <tbody>
    <%= render :partial => @posts.reverse %>
  </tbody>
</table>

app/views/posts/create.js.erb
// update post.
$('#posts').prepend('<%= escape_javascript(render @post) %>');

// simple fade effect to show the first item is entered..
$('#posts tbody tr:first').fadeTo('fast', '0.0');
$('#posts tbody tr:first').fadeTo('slow', '1');

// clears out the form.
$('#post_form > form')[0].reset();

// need to delete and reload the div.
// 1. deletes the div.
// 2. load the div again after the text entry box which is right before the div.
$('#post_current').remove();
$('#post_form').append('<%= escape_javascript(render 'current') %>');

app/views/posts/destroy.js.erb
$('#<%= dom_id(@post) %>').css('background', 'yellow');
$('#<%= dom_id(@post) %>').hide('slow');

app/views/posts/index.html.erb
<%= render 'form' %>
<%= render 'current' %>
<%= render 'table' %>

app/views/posts/update.js.erb
// need to delete and reload the div.
$('table').replaceWith('<%= escape_javascript(render 'table') %>');